# ROBO-MARC Project web page style (Jekylll slate)
# https://github.com/pages-themes/slate 
#
theme: jekyll-theme-cayman
title: [WRS Future Convenience Store Challenge]
description: [WRS Future Convenience Store Challenge Project Web page]

